name: Hello World

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run container script
        run: ./container.sh

      - name: Run container script again
        run: ./container.sh

      - name: Build my Docker image
        run: docker build -t my-nginx-image .

      - name: Start my Docker container
        run: docker run -d --name my-web -p 8080:8000 my-nginx-image

      - name: Get webpage with curl
        run: curl http://localhost:8080

      - name: Remove my Docker container
        run: docker rm -f my-web

